heat_template_version: 2013-05-23


description: All-in-one WordPress stack


parameters:
  keypair_name:
    default: amaury-ext-compute
    description: Keypair to inject in instances
    type: string

resources:
  network:
    type: OS::Neutron::Net
      
  subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: network }
      ip_version: 4
      cidr: 10.0.3.0/24
      allocation_pools:
        - { start: 10.0.3.100, end: 10.0.3.199 }

  security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - { direction: ingress, protocol: TCP, port_range_min: 22, port_range_max: 22 }
        - { direction: ingress, protocol: TCP, port_range_min: 80, port_range_max: 80 }
        - { direction: ingress, protocol: TCP, port_range_min: 443, port_range_max: 443 }
        - { direction: ingress, protocol: ICMP }
        - { direction: egress, protocol: ICMP }
        - { direction: egress, protocol: TCP }
        - { direction: egress, protocol: UDP }

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: 6ea98324-0f14-49f6-97c0-885d1b8dc517

  server:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: keypair_name }
      image: $IMAGE$
      flavor: s1.cw.small-1
      networks:
        - network: { get_resource: network }
      security_groups:
        - { get_resource: security_group }
      user_data_format: RAW
      user_data: |
        #!/bin/bash
        mkdir /etc/ansible
        echo "[local]" >> /etc/ansible/hosts
        echo "127.0.0.1 ansible_connection=local" >> /etc/ansible/hosts
        cd /root && git clone https://github.com/cloudwatt/applications.git cw-app
        ansible-playbook /root/cw-app/bundle-trusty-wordpress/seed-mysql.yml
        rm -rf /root/cw-app
        
  floating_ip_link:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: { get_resource: floating_ip }
      server_id: { get_resource: server }
